name: Terraform Workflow
on: workflow_dispatch

permissions:
  id-token: write   # required for OIDC
  contents: read    # required for checkout

jobs:
  terraform:
    runs-on: Runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -out=tfplan -detailed-exitcode || exit_code=$?
          if [ -z "$exit_code" ]; then
            exit_code=$?
          fi
          echo "plan_exit_code=$exit_code" >> $GITHUB_OUTPUT

      - name: Show Plan
        if: steps.plan.outputs.plan_exit_code == '2'
        run: terraform show -no-color tfplan

      - name: Terraform Apply
        if: steps.plan.outputs.plan_exit_code == '2'
        run: terraform apply -input=false -no-color -auto-approve tfplan
