name: "Infra Workflow"
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: c7135aa6-5c0c-4b33-a148-10aa1572b218
          tenant-id: de80a58f-1610-4908-a1a7-862be272a38c
          subscription-id: 0f48ce1f-16d2-42ba-8b4f-0bef1a58b563

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false


          
    
      
    
    
