name: Terraform Workflow
on: workflow_dispatch

permissions:
  id-token: write   # required for OIDC
  contents: read    # required for checkout

jobs:
  terraform:
    runs-on: Runner   # your self-hosted Windows runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        run: terraform init -input=false -no-color
        shell: pwsh

      - name: Terraform Validate
        run: terraform validate -no-color
        shell: pwsh

      - name: Terraform Plan
        id: plan
        shell: pwsh
        run: |
          terraform plan -input=false -no-color -out=tfplan -detailed-exitcode
          $exit_code = $LASTEXITCODE
          echo "plan_exit_code=$exit_code" >> $env:GITHUB_OUTPUT
          exit $exit_code

      - name: Show Plan
        if: steps.plan.outputs.plan_exit_code == '2'
        run: terraform show -no-color tfplan
        shell: pwsh

      - name: Terraform Apply
        if: steps.plan.outputs.plan_exit_code == '2'
        run: terraform apply -input=false -no-color -auto-approve tfplan
        shell: pwsh
