name: Terraform Workflow (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -input=false -no-color

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -out=tfplan -detailed-exitcode
          $exit_code = $LASTEXITCODE
          Write-Host "Terraform plan exit code: $exit_code"
          "exit_code=$exit_code" | Out-File -FilePath $env:GITHUB_ENV -Append
          exit 0  # don’t fail here, handle with conditions

      - name: Terraform Apply
        if: env.exit_code == '2'
        run: terraform apply -input=false -auto-approve tfplan

      - name: No Changes Detected
        if: env.exit_code == '0'
        run: echo "No changes detected, skipping apply."

      - name: Terraform Plan Failed
        if: env.exit_code == '1'
        run: exit 1
